#!/bin/sh

### BEGIN INIT INFO
# Provides:          neo4j
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops neo4j server
# Description:       Starts and stops neo4j server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

NAME=neo4j
DESC="Neo4j server"
NEO4J_HOME=/opt/neo4j/current
NEO4J_CONF=/opt/neo4j/conf

case "$1" in
  start)
    echo -n "Starting $DESC: "
    su - root -c "/opt/neo4j/current/bin/neo4j start > /var/log/neo4j"
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    su - root -c "/opt/neo4j/current/bin/neo4j stop > /var/log/neo4j"
    echo "$NAME."
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;

esac

exit 0
