#!/bin/sh

### BEGIN INIT INFO
# Provides:          rcb-neo4j-queries
# Required-Start:    $local_fs $network $syslog $neo4j
# Required-Stop:     $local_fs $network $syslog $neo4j
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops neo4j queries led script
# Description:       Starts and stops neo4j queries led script
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/home/pi/rasp_cluster_box/queries/query-log-led.py
NAME=rcb-neo4j-queries
DESC="rcb-neo4j-queries script"

USER=root

. /lib/lsb/init-functions

[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --chuid ${USER} --start --quiet --pidfile /var/run/$NAME.pid --background --make-pidfile --exec $DAEMON
    echo "$NAME."
    ;;
  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --chuid ${USER} --stop --oknodo --quiet --pidfile /var/run/$NAME.pid
    echo "$NAME."
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 1
    ;;

esac

exit 0
